import type { FinanceState } from "./types";

export const SEED_DATA: FinanceState = {
  categories: [
    { id: "cat_salary", name: "Salary", type: "income" },
    { id: "cat_freelance", name: "Freelance", type: "income" },
    { id: "cat_food", name: "Food", type: "expense" },
    { id: "cat_rent", name: "Rent", type: "expense" },
    { id: "cat_transport", name: "Transport", type: "expense" },
    { id: "cat_shopping", name: "Shopping", type: "expense" },
    { id: "cat_utilities", name: "Utilities", type: "expense" },
  ],
  transactions: [
    {
      id: "tx_1",
      amount: 85000,
      type: "income",
      note: "September salary",
      date: "2026-09-01",
      categoryId: "cat_salary",
    },
    {
      id: "tx_2",
      amount: 12000,
      type: "income",
      note: "Weekend project",
      date: "2026-09-10",
      categoryId: "cat_freelance",
    },
    {
      id: "tx_3",
      amount: 18000,
      type: "expense",
      note: "Apartment rent",
      date: "2026-09-02",
      categoryId: "cat_rent",
    },
    {
      id: "tx_4",
      amount: 4200,
      type: "expense",
      note: "Groceries + lunch",
      date: "2026-09-08",
      categoryId: "cat_food",
    },
    {
      id: "tx_5",
      amount: 1800,
      type: "expense",
      note: "Metro + auto",
      date: "2026-09-12",
      categoryId: "cat_transport",
    },
    {
      id: "tx_6",
      amount: 3500,
      type: "expense",
      note: "Electricity + wifi",
      date: "2026-09-05",
      categoryId: "cat_utilities",
    },
    {
      id: "tx_7",
      amount: 2600,
      type: "expense",
      note: "New headphones case",
      date: "2026-09-15",
      categoryId: "cat_shopping",
    },
    {
      id: "tx_8",
      amount: 82000,
      type: "income",
      note: "August salary",
      date: "2026-08-01",
      categoryId: "cat_salary",
    },
    {
      id: "tx_9",
      amount: 18000,
      type: "expense",
      note: "August rent",
      date: "2026-08-02",
      categoryId: "cat_rent",
    },
    {
      id: "tx_10",
      amount: 5100,
      type: "expense",
      note: "August groceries",
      date: "2026-08-18",
      categoryId: "cat_food",
    },
  ],
};
